POST http://localhost:8080/books
Content-Type: application/json

{
  "author": "Jane Austen",
  "title": "Pride and Prejudice",
  "gender": "romance"
}
###

POST http://localhost:8080/books
Content-Type: application/json

{
  "author": "F. Scott Fitzgerald",
  "title": "The Great Gatsby",
  "gender": "drama"
}
###

POST http://localhost:8080/books
Content-Type: application/json

{
  "author": "C.S. Lewis",
  "title": "The Lion, the Witch and the Wardrobe",
  "gender": "fantasy"
}
###

GET http://localhost:8080/books?title=The%20Great%20Gatsby
###

GET http://localhost:8080/books?title=The%20Great%20Gatsby&pageNumber=0&pageSize=1
###

GET http://localhost:8080/books
###

GET http://localhost:8080/books/6179b76c-a80e-4f80-abd5-29985b83decf
###